### ISSUE TITLE
Array index out-of-bounds (index -1, limit 66)

### ISSUE THREAD

**Issue by xSL0W** [NotJustin/SkillAutoBalance#9] opened 2020-06-01 22:29 UTC
Using:
public Plugin myinfo =
{
	name = "SABREMAKE",
	author = "Justin (ff)",
	description = "Balance teams when one side is stacked",
	version = "3.0.2",
	url = "https://steamcommunity.com/id/NameNotJustin/"
}

L 06/02/2020 - 01:00:11: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 06/02/2020 - 01:00:11: [SM] Blaming: tools/skillautobalance.smx
L 06/02/2020 - 01:00:11: [SM] Call stack trace:
L 06/02/2020 - 01:00:11: [SM]   [1] Line 793, c:\Users\xSLOW\Desktop\compilerV2\source\skillautobalance.sp::RemoveOutliers
L 06/02/2020 - 01:00:11: [SM]   [2] Line 942, c:\Users\xSLOW\Desktop\compilerV2\source\skillautobalance.sp::BalanceSkill
L 06/02/2020 - 01:00:11: [SM]   [3] Line 671, c:\Users\xSLOW\Desktop\compilerV2\source\skillautobalance.sp::GetScore
L 06/02/2020 - 01:00:11: [SM]   [4] Line 959, c:\Users\xSLOW\Desktop\compilerV2\source\skillautobalance.sp::OnClientPostAdminCheck

// This file was auto-generated by SourceMod (v1.10.0.6488)
// ConVars for plugin "tools/skillautobalance.smx"

// Prevent clients from switching team. Can join spectate. Can switch if it is impossible for them to rejoin same team due to team-size
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sab_blockteamswitch "0"

// Enable joining teams by chat commands '!join, !play, !j, !p, !spectate, !spec, !s (no picking teams)
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sab_chatchangeteam "0"

// The amount to subtract from a streak if UseDecay is true. In other words, the ratio of a team's round wins to the opposing team's must be greater than this number in order for a team balance to eventually occur.
// -
// Default: "1.5"
// Minimum: "1.000000"
sab_decayamount "1.5"

// Allow plugin to display messages in the chat
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sab_displaychatmessages "1"

// Add 'force balance' to 'server commands' in generic admin menu
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sab_forcebalance "1"

// Force clients to join a team upon connecting to the server. If both sab_chatchangeteam and sab_teammenu are disabled, this will always be enabled (otherwise, clients cannot join a team).
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sab_forcejointeam "0"

// Living players are kept alive when their teams are changed
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sab_keepplayersalive "1"

// See sab_messagetype for info
// -
// Default: "white"
sab_messagecolor "white"

// How this plugin's messages will be colored in chat. 0 = no color, 1 = color only prefix with sab_prefixcolor, 2 = color entire message with sab_messagecolor, 3 = color prefix and message with both sab_prefixcolor and sab_messagecolor
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "3.000000"
sab_messagetype "0"

// The amount of players not in spectate must be at least this number for a balance to occur
// -
// Default: "10"
// Minimum: "2.000000"
sab_minplayers "10"

// Amount of wins in a row a team needs before autobalance occurs
// -
// Default: "4"
// Minimum: "0.000000"
sab_minstreak "4"

// The prefix for messages this plugin writes in the server
// -
// Default: "[TeamBalance]"
sab_prefix "[TeamBalance]"

// See sab_messagetype for info
// -
// Default: "red"
sab_prefixcolor "red"

// Formula used to determine player 'skill'. 0 = K/D, 1 = 2*K/D, 2 = K^2/D, 3 = gameME rank, 4 = RankME, 5 = LVL Ranks
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "5.000000"
sab_scoretype "0"

// Randomize teams instead of using a skill formula
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sab_scramble "0"

// Add 'set player team' to 'player commands' in generic admin menu
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sab_setteam "0"

// Whether to enable or disable the join team menu.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sab_teammenu "1"

// If 1, subtract sab_decayamount from a team's streak when they lose instead of setting their streak to 0
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sab_usedecay "1"

**Comment by NotJustin** [comment] 2020-06-02 19:55
Closing. Reopen if issue still happens @xSL0W

**Comment by WhyFaust** [comment] 2020-06-09 07:48
By the way, the bug wasn't fixed, I'm still seeing it at my place, although I have updated the plugin to the latest version.

**Comment by NotJustin** [comment] 2020-06-09 19:10
It is caused by my "fix" to #8 which is still broken.

I have the fix for this index-out-of-bound bug but I cannot push what I currently have until I fix #8.

**Closed as completed** 2020-06-11 08:15 UTC
